apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio 
  strategy:
    type: Recreate
    activeDeadlineSeconds: 21600
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: "minio-pv-claim"
      containers:
        
      - name: minio1
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        volumeMounts:
        - name: data 
          mountPath: "/data" 
        args:
        - server
        - /data
        - --address 
        - ":9001"
        ports:
        - containerPort: 9001
        resources:
            limits:
              memory: 300Mi
              cpu: 0.5
            requests:
              cpu: 0.2
              memory: 100Mi
        env:
        # MinIO access key and secret key
        - name: MINIO_ACCESS_KEY
          valueFrom:
                secretKeyRef:
                  key: minioAccessKey
                  name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
                secretKeyRef:
                  key: minioSecretKey
                  name: minio
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9001
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9001
          initialDelaySeconds: 120
          periodSeconds: 20

      - name: minio2
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        volumeMounts:
        - name: data 
          mountPath: "/data" 
        args:
        - server
        - /data
        - --address 
        - ":9002"
        ports:
        - containerPort: 9002
        resources:
            limits:
              memory: 300Mi
              cpu: 0.5
            requests:
              cpu: 0.2
              memory: 100Mi
        env:
        # MinIO access key and secret key
        - name: MINIO_ACCESS_KEY
          valueFrom:
                secretKeyRef:
                  key: minioAccessKey
                  name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
                secretKeyRef:
                  key: minioSecretKey
                  name: minio
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9002
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9002
          initialDelaySeconds: 120
          periodSeconds: 20

      - name: minio3
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        volumeMounts:
        - name: data 
          mountPath: "/data" 
        args:
        - server
        - /data
        - --address 
        - ":9003"
        ports:
        - containerPort: 9003
        resources:
            limits:
              memory: 300Mi
              cpu: 0.5
            requests:
              cpu: 0.2
              memory: 100Mi
        env:
        # MinIO access key and secret key
        - name: MINIO_ACCESS_KEY
          valueFrom:
                secretKeyRef:
                  key: minioAccessKey
                  name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
                secretKeyRef:
                  key: minioSecretKey
                  name: minio
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9003
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9003
          initialDelaySeconds: 120
          periodSeconds: 20

      - name: minio4
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        volumeMounts:
        - name: data 
          mountPath: "/data" 
        args:
        - server
        - /data
        - --address 
        - ":9004"
        ports:
        - containerPort: 9004
        resources:
            limits:
              memory: 300Mi
              cpu: 0.5
            requests:
              cpu: 0.2
              memory: 100Mi
        env:
        # MinIO access key and secret key
        - name: MINIO_ACCESS_KEY
          valueFrom:
                secretKeyRef:
                  key: minioAccessKey
                  name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
                secretKeyRef:
                  key: minioSecretKey
                  name: minio
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9004
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9004
          initialDelaySeconds: 120
          periodSeconds: 20






  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #   spec:
  #     accessModes: [ "ReadWriteMany" ]
  #     storageClassName: gp2
  #     resources:
  #       requests:
  #         storage: 100Mi


