---
kind: Template
apiVersion: v1
metadata:
  name: minio
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    selector:
      app: "${NAME}"

    strategy:
      type: Recreate
      resources: {}
      activeDeadlineSeconds: 21600

    replicas: 1
    
    template:
      metadata:
        creationTimestamp: 
        labels:
          app: "${NAME}"
      spec:
        volumes:
        - name: "${NAME}-vol"
          persistentVolumeClaim:
            claimName: "${NAME}-pv-claim"

        containers:
          # minio-1
        - name: "${NAME}-1"
          image: minio/minio:RELEASE.2019-10-12T01-39-57Z
          args:
          - server
          - /data
          - --address 
          - ":9001"
          ports:
          - containerPort: 9001
            protocol: TCP
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioSecretKey
          - name: MINIO_CONFIG_DIR
            value: "/tmp"
          - name: MINIO_DATA_DIR
            value: "/data"
          resources: {}
          volumeMounts:
          - name: "${NAME}-vol"
            mountPath: "/data"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always

          # minio-2
        - name: "${NAME}-2"
          image: minio/minio:RELEASE.2019-10-12T01-39-57Z
          args:
          - server
          - /data
          - --address 
          - ":9002"
          ports:
          - containerPort: 9002
            protocol: TCP
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioSecretKey
          - name: MINIO_CONFIG_DIR
            value: "/tmp"
          - name: MINIO_DATA_DIR
            value: "/data"
          resources: {}
          volumeMounts:
          - name: "${NAME}-vol"
            mountPath: "/data"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always

          # minio-3
        - name: "${NAME}-3"
          image: minio/minio:RELEASE.2019-10-12T01-39-57Z
          args:
          - server
          - /data
          - --address 
          - ":9003"
          ports:
          - containerPort: 9003
            protocol: TCP
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioSecretKey
          - name: MINIO_CONFIG_DIR
            value: "/tmp"
          - name: MINIO_DATA_DIR
            value: "/data"
          resources: {}
          volumeMounts:
          - name: "${NAME}-vol"
            mountPath: "/data"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always

          # minio-4
        - name: "${NAME}-4"
          image: minio/minio:RELEASE.2019-10-12T01-39-57Z
          args:
          - server
          - /data
          - --address 
          - ":9004"
          ports:
          - containerPort: 9004
            protocol: TCP
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: minioSecretKey
          - name: MINIO_CONFIG_DIR
            value: "/tmp"
          - name: MINIO_DATA_DIR
            value: "/data"
          resources: {}
          volumeMounts:
          - name: "${NAME}-vol"
            mountPath: "/data"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
          
          # NGINX Container
        - name: nginx    
          image: gitlabregistry.sparktech.ro/ignite/infrastructure/nginx_minio_lb
          resources: {}
          ports:
          - containerPort: 8081
            protocol: TCP

        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status: {}


- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "${NAME}-pv-claim"
    labels:
      app: "${NAME}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"
  status: {}

- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels:
      app: "${NAME}"
  spec:
    type: LoadBalancer
    ports:
      - name: "${NAME}-1"
        port: 9001
        targetPort: 9001
        protocol: TCP
      - name: "${NAME}-2"
        port: 9002
        targetPort: 9002
        protocol: TCP
      - name: "${NAME}-3"
        port: 9003
        targetPort: 9003
        protocol: TCP
      - name: "${NAME}-4"
        port: 9004
        targetPort: 9004
        protocol: TCP
      - name: "nginx"
        port: 8081
        targetPort: 8081
        protocol: TCP
    selector:
      app: "${NAME}"
  status:
      loadBalancer: {}


- kind: Secret
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  stringData:
    minioAccessKey: "${MINIO_ACCESS_KEY}"
    minioSecretKey: "${MINIO_SECRET_KEY}"


parameters:
- name: NAME
  displayName: Name to apply to objects in the template
  value: minio
  required: true
- name: MINIO_ACCESS_KEY
  displayName: Minio access key
  generate: expression
  from: "[a-zA-Z0-9]{8}"
  required: true
- name: MINIO_SECRET_KEY
  displayName: Minio secret key
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: VOLUME_CAPACITY
  displayName: Volume Capacity
  description: Volume space available to Minio server for files, e.g. 512Mi, 2Gi.
  value: 1Gi
  required: true