apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: minio1
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: minio2
      port: 9002
      targetPort: 9002
      protocol: TCP
    - name: minio3
      port: 9003
      targetPort: 9003
      protocol: TCP
    - name: minio4
      port: 9004
      targetPort: 9004
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio