apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx    
        image: # insert here link to docker image
        resources:
            limits:
              memory: 200Mi
              cpu: 0.5
            requests:
              cpu: 0.2
              memory: 100Mi
        ports:
        - containerPort: 8081
        