apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: nginx